---
- hosts: all
  tasks:
    - name: Update Packages on Debian nodes
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: dist
        name: "*"
        state: latest
      when: ansible_os_family == 'Debian'

- hosts: all
  tasks:
    - name: Update Packages on RedHat nodes
      yum:
        update_cache: yes
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat'